/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_appsync_graphqlEndpoint": "https://jcc73n63c5b6fjx3bggyjfjyca.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-g5zsrkjcjbfzrfxdmcwbsv25rq",
    "aws_cognito_identity_pool_id": "ca-central-1:eeb5409d-99e6-4f66-8962-0d8c66e39ce4",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_xrWXBCcRH",
    "aws_user_pools_web_client_id": "7shm2i28eo3886g1lalcjhdec1",
    "oauth": {}
};


export default awsmobile;
