/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:7ffe1472-d5a6-411c-a78b-c4846e52be07",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_qawbIb4Ld",
    "aws_user_pools_web_client_id": "78963d1lr11lhjiqvav05pul2h",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://eodo5xnhfzabtdijcruzfnkxxi.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-huat37sleraptj2hx3xxvm267u"
};


export default awsmobile;
